In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import SimpleRNN, LSTM, Bidirectional


In [4]:
X_train=np.random.random((1,4,5))
# 문장의 길이가 4이고 단어의 벡터가 5인 경우 
# 즉, 4번의 시점이 존재하고, 각 시점마다 5차원의 단어벡터가 입력으로 사용됨 
# batch_size가 1

## RNN

In [6]:
rnn= SimpleRNN(3) # 은닉 상태를 3으로 지정
hidden_state=rnn(X_train)
print(hidden_state)
hidden_state.shape

tf.Tensor([[0.35173148 0.84430665 0.96924275]], shape=(1, 3), dtype=float32)


TensorShape([1, 3])

In [9]:
# 모든 시점의 은닉 상태 출력 
rnn= SimpleRNN(3,return_sequences=True) # 은닉 상태를 3으로 지정
hidden_state=rnn(X_train)
print(hidden_state)
hidden_state.shape

tf.Tensor(
[[[-0.60711676  0.5254308  -0.7699579 ]
  [-0.96744573 -0.5893576  -0.8123448 ]
  [-0.9827054   0.6804485  -0.8937508 ]
  [-0.9809829  -0.87479895 -0.87841606]]], shape=(1, 4, 3), dtype=float32)


TensorShape([1, 4, 3])

In [12]:
# 모든 시점의 은닉 상태 출력 
rnn= SimpleRNN(3,return_state=True,return_sequences=True) # 은닉 상태를 3으로 지정
hidden_state=rnn(X_train)
hidden_state # 마지막, 모든 시점 모두 출력 

(<tf.Tensor: shape=(1, 4, 3), dtype=float32, numpy=
 array([[[ 0.2825431 , -0.61816096, -0.1304721 ],
         [ 0.5001664 , -0.0368742 ,  0.5530929 ],
         [ 0.85117483, -0.9208489 , -0.4091828 ],
         [ 0.93318224, -0.16590558, -0.26191142]]], dtype=float32)>,
 <tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[ 0.93318224, -0.16590558, -0.26191142]], dtype=float32)>)

## LSTM
- 마지막 은닉
- 모든 은닉 
- 마지막 cell state

In [14]:
lstm = LSTM(3, return_sequences=True, return_state=True)
hidden_states, last_hidden_state, last_cell_state = lstm(X_train)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('last hidden state : {}, shape: {}'.format(last_hidden_state, last_hidden_state.shape))
print('last cell state : {}, shape: {}'.format(last_cell_state, last_cell_state.shape))


hidden states : [[[ 0.08797897 -0.03385496  0.1893196 ]
  [ 0.05482988 -0.01693342  0.29554683]
  [ 0.07788294 -0.04160867  0.36548486]
  [ 0.1319064  -0.02133337  0.47830945]]], shape: (1, 4, 3)
last hidden state : [[ 0.1319064  -0.02133337  0.47830945]], shape: (1, 3)
last cell state : [[ 0.31160527 -0.06836465  1.0957663 ]], shape: (1, 3)
